import {PlayerState} from "./core/PlayerState.js";
import {MediaEngine} from "./core/MediaEngine.js";
import {QueueManager} from "./core/QueueManager.js";
import {PlaylistManager} from "./core/PlaylistManager.js";
import {LibraryManager} from "./core/LibraryManager.js";
import {HistoryManager} from "./core/HistoryManager.js";
import {IndexedDBStore} from "./storage/IndexedDB.js";
import {Toast} from "./ui/Toast.js";
import {QueueUI} from "./ui/QueueUI.js";
import {LibraryUI} from "./ui/LibraryUI.js";
import {AudioEngine} from "./audio/AudioEngine.js";
import {Equalizer} from "./audio/Equalizer.js";
import {Visualizer} from "./audio/Visualizer.js";
import {VideoFilters} from "./video/VideoFilters.js";
import {SubtitleManager} from "./video/SubtitleManager.js";
import {Screenshot} from "./video/Screenshot.js";
import {ThemeManager} from "./features/ThemeManager.js";
import {FullscreenManager} from "./features/FullscreenManager.js";
import {KeyboardShortcuts} from "./features/KeyboardShortcuts.js";
import {ABRepeat} from "./features/ABRepeat.js";
import {ResumePlayback} from "./features/ResumePlayback.js";
import {registerPWA} from "./pwa/pwa.js";
import {MediaSession} from "./features/MediaSession.js";
const $=id=>document.getElementById(id),state=new PlayerState(),store=new IndexedDBStore(),toast=new Toast($("toast-root")),media=$("media-element");
const engine=new MediaEngine(media,state),queue=new QueueManager(),library=new LibraryManager(store),history=new HistoryManager(store),playlists=new PlaylistManager(store),theme=new ThemeManager(),audio=new AudioEngine(media),visualizer=new Visualizer($("visualizer-canvas"),audio),filters=new VideoFilters(media),subtitles=new SubtitleManager(media),shot=new Screenshot(media),fullscreen=new FullscreenManager($("media-canvas")),ab=new ABRepeat(engine),resume=new ResumePlayback(history);
const ui={play:$("play-btn"),stagePlay:$("stage-play"),seek:$("seek-range"),volume:$("volume-range"),mute:$("mute-btn"),prev:$("prev-btn"),next:$("next-btn"),shuffle:$("shuffle-btn"),repeat:$("repeat-btn"),speed:$("speed-btn"),fullscreen:$("fullscreen-btn"),pip:$("pip-btn"),current:$("current-time"),duration:$("duration-time"),nowTitle:$("now-title"),nowMeta:$("now-meta"),mini:$("mini-player"),miniTitle:$("mini-title"),miniMeta:$("mini-meta"),miniPlay:$("mini-play"),miniPrev:$("mini-prev"),miniNext:$("mini-next"),miniBar:$("mini-progress-bar"),art:$("artwork-fallback")};
const icon=n=>'<i data-lucide="'+n+'"></i>';function icons(){window.lucide?.createIcons?.()}function formatTime(s){s=Math.max(0,Math.floor(s||0));return Math.floor(s/60)+":"+String(s%60).padStart(2,"0")}
function renderState(s){ui.play.innerHTML=s.isPlaying?icon("pause"):icon("play");ui.stagePlay.innerHTML=s.isPlaying?icon("pause"):icon("play");ui.stagePlay.classList.toggle("hidden",!s.media);ui.nowTitle.textContent=s.media?.title||"Nothing playing";ui.nowMeta.textContent=s.media?((s.media.artist||"Local file")+" • "+s.media.type.toUpperCase()):"Select media from your library";ui.current.textContent=formatTime(s.currentTime);ui.duration.textContent=formatTime(s.duration);ui.seek.value=s.duration?(s.currentTime/s.duration)*100:0;ui.volume.value=s.volume;ui.speed.textContent=(s.rate||1)+"×";ui.mute.innerHTML=icon(s.muted||s.volume===0?"volume-x":"volume-2");ui.mini.classList.toggle("hidden",!s.media);ui.miniTitle.textContent=s.media?.title||"Nothing playing";ui.miniMeta.textContent=s.media?.artist||"Local file";ui.miniBar.style.width=(s.duration?(s.currentTime/s.duration)*100:0)+"%";$("video-badge").classList.toggle("hidden",s.media?.type!=="video");ui.art.classList.toggle("hidden",s.media?.type!=="audio");icons()}
function renderLibrary(view="home",query=""){let items=library.search(query);if(view==="music")items=items.filter(i=>i.type==="audio");if(view==="videos")items=items.filter(i=>i.type==="video");if(view==="favorites")items=items.filter(i=>i.favorite);if(view==="history"){const ids=history.ids();items=items.filter(i=>ids.has(i.id)).sort((a,b)=>(history.position(b.id)-history.position(a.id)))}libUI.render(items)}
function setView(view){state.patch({view});document.querySelectorAll(".nav-item[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===view));$("player-view").classList.toggle("hidden",view!=="player");$("library-view").classList.toggle("hidden",view==="player");const t={home:["YOUR LIBRARY","Home","Open local media and build your personal library."],music:["AUDIO COLLECTION","Music","All audio files in your library."],videos:["VIDEO COLLECTION","Videos","All video files in your library."],favorites:["YOUR FAVORITES","Favorites","Media you marked as favorite."],history:["RECENTLY PLAYED","History","Continue from where you left off."]}[view]||null;if(t){$("view-eyebrow").textContent=t[0];$("view-title").textContent=t[1];$("view-description").textContent=t[2]}renderLibrary(view,$("global-search").value)}
async function playItem(item,index=-1){if(!item)return;if(index>=0)queue.index=index;else{const found=queue.items.findIndex(x=>x.id===item.id);if(found<0)queue.add(item);queue.index=queue.items.findIndex(x=>x.id===item.id)}setView("player");const remembered=resume.get(item);await engine.load(item,false);const onMeta=()=>{if(remembered>5&&remembered<engine.duration-8)engine.seek(remembered)};if(media.readyState>=1)onMeta();else media.addEventListener("loadedmetadata",onMeta,{once:true});try{await audio.resume()}catch{}await engine.play().catch(()=>toast.show("Playback was blocked; press play again","error"));visualizer.start()}
function next(){const item=queue.next();if(item)playItem(item,queue.index)}
function previous(){const item=queue.previous();if(item)playItem(item,queue.index)}
const libUI=new LibraryUI($("media-grid"),$("empty-state"),library,{play:playItem,queue:item=>{queue.add(item);toast.show("Added to queue")},playlist:item=>openPlaylistPicker(item),favorite:item=>{library.toggleFavorite(item.id)}});
new QueueUI($("queue-list"),$("queue-empty"),$("queue-count"),queue,{select:i=>{queue.index=i;playItem(queue.current(),i)}});
theme.init();await store.open();await library.init();await history.init();await playlists.init();library.on(items=>{$("music-count").textContent=items.filter(i=>i.type==="audio").length;$("video-count").textContent=items.filter(i=>i.type==="video").length;renderLibrary(state.data.view)});
state.subscribe(renderState);
$("open-import").onclick=$("browse-library").onclick=$("drop-browse").onclick=$("empty-browse").onclick=()=>$("file-input").click();
$("clear-queue").onclick=()=>{queue.clear();toast.show("Queue cleared")};
ui.play.onclick=ui.miniPlay.onclick=()=>engine.toggle().catch(()=>{});ui.stagePlay.onclick=()=>engine.toggle().catch(()=>{});
ui.prev.onclick=ui.miniPrev.onclick=previous;ui.next.onclick=ui.miniNext.onclick=next;ui.seek.oninput=e=>engine.seek(engine.duration*(Number(e.target.value)/100));ui.volume.oninput=e=>engine.setVolume(e.target.value);ui.mute.onclick=()=>engine.toggleMute();
ui.shuffle.onclick=()=>{queue.setShuffle(!queue.shuffle);ui.shuffle.classList.toggle("active",queue.shuffle)};ui.repeat.onclick=()=>{const v=queue.repeat==="off"?"all":queue.repeat==="all"?"one":"off";queue.setRepeat(v);ui.repeat.classList.toggle("active",v!=="off");toast.show("Repeat: "+v)};
ui.speed.onclick=()=>{const r=[.5,.75,1,1.25,1.5,1.75,2],i=r.indexOf(media.playbackRate);engine.setRate(r[(i+1)%r.length])};ui.fullscreen.onclick=()=>fullscreen.toggle();ui.pip.onclick=()=>media.requestPictureInPicture?.().catch(()=>toast.show("Picture in Picture unavailable","error"));
let lastHistorySave=0;media.addEventListener("ended",()=>next());media.addEventListener("error",()=>toast.show("This browser could not decode the selected media","error"));media.addEventListener("timeupdate",()=>{ab.update();const now=Date.now();if(state.data.media&&state.data.currentTime>1&&now-lastHistorySave>5000){lastHistorySave=now;history.touch(state.data.media,state.data.currentTime).then(()=>{if(state.data.view==="history")renderLibrary("history")}).catch(()=>{})}});
$("file-input").onchange=async e=>{const fs=[...e.target.files];if(!fs.length)return;const a=await library.addFiles(fs);queue.addMany(a);toast.show(a.length+" media item"+(a.length===1?"":"s")+" added");e.target.value=""};
const dz=$("drop-zone");["dragenter","dragover"].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add("is-over")}));dz.addEventListener("dragleave",()=>dz.classList.remove("is-over"));dz.addEventListener("drop",async e=>{e.preventDefault();dz.classList.remove("is-over");const a=await library.addFiles([...e.dataTransfer.files]);if(a.length){queue.addMany(a);toast.show(a.length+" media item(s) added")}});
$("global-search").oninput=e=>renderLibrary(state.data.view,e.target.value);$("sort-library").onclick=()=>{library.items.sort((a,b)=>a.title.localeCompare(b.title));renderLibrary(state.data.view)};
document.querySelectorAll(".nav-item[data-view]").forEach(b=>b.onclick=()=>setView(b.dataset.view));$("sidebar-toggle").onclick=()=>document.body.classList.toggle("sidebar-open");$("mini-close").onclick=()=>ui.mini.classList.add("hidden");
$("tool-screenshot").onclick=()=>{try{shot.capture();toast.show("Frame captured")}catch(e){toast.show(e.message,"error")}};$("tool-subtitles").onclick=()=>$("subtitle-input").click();$("subtitle-input").onchange=e=>{const f=e.target.files[0];if(f){subtitles.load(f);toast.show("Subtitle loaded")}};
$("tool-video").onclick=()=>openVideoModal();$("tool-eq").onclick=()=>openEQModal();$("tool-info").onclick=()=>openInfoModal();$("tool-ab").onclick=()=>{const st=ab.status();if(st.a===null){toast.show("A set at "+formatTime(ab.setA()))}else if(st.b===null){toast.show("B set at "+formatTime(ab.setB())+" • Loop active")}else{ab.clear();toast.show("A–B loop cleared")}};
$("open-equalizer").onclick=openEQModal;$("open-settings").onclick=openSettingsModal;$("open-command").onclick=openCommandModal;$("open-shortcuts").onclick=()=>toast.show("Space play/pause • ←/→ seek • ↑/↓ volume • M mute • N next • P previous • F fullscreen • E equalizer • A–B button sets loop points");
$("new-playlist").onclick=async()=>{const name=prompt("Playlist name");if(name){await playlists.create(name);renderPlaylists();toast.show("Playlist created")}};
function modal(title,body,actions=""){const root=$("modal-root");root.innerHTML='<div class="modal-backdrop"><div class="modal">'+title+body+actions+"</div></div>";const bd=root.firstElementChild;bd.onclick=e=>{if(e.target===bd)root.innerHTML=""};root.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>root.innerHTML="");icons()}
function openEQModal(){const bands=[60,170,310,600,1000,3000,6000,10000,14000,16000];modal("<div class='modal-head'><div class='modal-title'>10-Band Equalizer</div><button class='icon-btn' data-close>×</button></div>","<div class='modal-body'><div class='eq-grid'>"+bands.map((b,i)=>"<label class='eq-band'><input data-band='"+i+"' type='range' min='-12' max='12' value='0'><span>"+(b>=1000?(b/1000)+"k":b)+"</span></label>").join("")+"</div><div class='preset-row'>"+["Flat","Rock","Pop","Bass","Vocal"].map(p=>"<button class='soft-btn' data-preset='"+p+"'>"+p+"</button>").join("")+"</div></div>","<div class='modal-actions'><button class='primary-btn' data-close>Done</button></div>");try{audio.ensure()}catch{}const eq=new Equalizer(audio);document.querySelectorAll("[data-band]").forEach(x=>x.oninput=e=>audio.setBand(Number(e.target.dataset.band),e.target.value));document.querySelectorAll("[data-preset]").forEach(x=>x.onclick=()=>{eq.preset(x.dataset.preset);eq.presets[x.dataset.preset].forEach((v,i)=>document.querySelector('[data-band="'+i+'"]').value=v)})}
function openVideoModal(){modal("<div class='modal-head'><div class='modal-title'>Video filters</div><button class='icon-btn' data-close>×</button></div>","<div class='modal-body'><div class='field'><label>Brightness</label><input data-filter='brightness' type='range' min='50' max='150' value='100'></div><div class='field'><label>Contrast</label><input data-filter='contrast' type='range' min='50' max='150' value='100'></div><div class='field'><label>Saturation</label><input data-filter='saturation' type='range' min='0' max='200' value='100'></div><div class='field'><label>Hue</label><input data-filter='hue' type='range' min='-90' max='90' value='0'></div><button id='reset-filters' class='soft-btn'>Reset</button></div>","<div class='modal-actions'><button class='primary-btn' data-close>Done</button></div>");document.querySelectorAll("[data-filter]").forEach(x=>x.oninput=e=>filters.set(e.target.dataset.filter,e.target.value));$("reset-filters").onclick=()=>{filters.reset();document.querySelectorAll("[data-filter]").forEach(x=>x.value=filters.values[x.dataset.filter])}}
function openInfoModal(){const i=state.data.media;if(!i)return toast.show("Nothing is playing","error");modal("<div class='modal-head'><div class='modal-title'>Media information</div><button class='icon-btn' data-close>×</button></div>","<div class='modal-body'><div class='settings-section'><div class='setting-line'><div class='setting-copy'><strong>Name</strong><span>"+i.name+"</span></div></div><div class='setting-line'><div class='setting-copy'><strong>MIME</strong><span>"+i.mime+"</span></div></div><div class='setting-line'><div class='setting-copy'><strong>Duration</strong><span>"+formatTime(i.duration)+"</span></div></div><div class='setting-line'><div class='setting-copy'><strong>Size</strong><span>"+(i.size/1048576).toFixed(2)+" MB</span></div></div></div></div>","<div class='modal-actions'><button class='primary-btn' data-close>Close</button></div>")}
function openPlaylistPicker(item){if(!playlists.playlists.length){toast.show("Create a playlist first","error");return}modal("<div class='modal-head'><div class='modal-title'>Add to playlist</div><button class='icon-btn' data-close>×</button></div>","<div class='modal-body'><div id='playlist-picker' class='command-list'></div></div>");const root=$("playlist-picker");playlists.playlists.forEach(p=>{const b=document.createElement("button");b.className="nav-item";b.textContent=p.name;b.onclick=async()=>{await playlists.addItem(p.id,item);$("modal-root").innerHTML="";toast.show("Added to "+p.name)}})}
function openSettingsModal(){modal("<div class='modal-head'><div class='modal-title'>AURA Settings</div><button class='icon-btn' data-close>×</button></div>","<div class='modal-body'><div class='settings-layout'><nav class='settings-nav'><button class='settings-tab active'>Appearance</button><button class='settings-tab'>Playback</button><button class='settings-tab'>Storage</button></nav><div class='settings-section'><div class='setting-line'><div class='setting-copy'><strong>Theme</strong><span>Dark or light application shell</span></div><select id='theme-select'><option value='dark'>Dark</option><option value='light'>Light</option></select></div><div class='setting-line'><div class='setting-copy'><strong>Visualizer</strong><span>Animate audio spectrum on the player</span></div><label class='switch'><input id='viz-switch' type='checkbox' checked><span></span></label></div><div class='setting-line'><div class='setting-copy'><strong>Clear history</strong><span>Remove local playback history</span></div><button id='clear-history' class='soft-btn'>Clear</button></div></div></div></div>","<div class='modal-actions'><button class='primary-btn' data-close>Done</button></div>");$("theme-select").value=document.body.dataset.theme;$("theme-select").onchange=e=>theme.set(e.target.value);$("viz-switch").onchange=e=>e.target.checked?visualizer.start():visualizer.stop();$("clear-history").onclick=()=>history.clear().then(()=>{renderLibrary(state.data.view);toast.show("History cleared")})}
function openCommandModal(){modal("<div class='modal-head'><div class='modal-title'>Command Palette</div><button class='icon-btn' data-close>×</button></div>","<div class='modal-body'><div class='field'><input id='command-search' autofocus placeholder='Search commands…'></div><div id='command-list' class='command-list'></div></div>");const commands=[["Play / Pause",()=>engine.toggle()],["Next",next],["Previous",previous],["Fullscreen",()=>fullscreen.toggle()],["Equalizer",openEQModal],["Add media",()=>$("file-input").click()],["Home",()=>setView("home")]];const draw=q=>{const list=$("command-list");list.innerHTML="";commands.filter(x=>x[0].toLowerCase().includes(q.toLowerCase())).forEach(x=>{const b=document.createElement("button");b.className="nav-item";b.textContent=x[0];b.onclick=()=>{$("modal-root").innerHTML="";x[1]()};list.append(b)})};$("command-search").oninput=e=>draw(e.target.value);draw("");$("command-search").focus()}
function renderPlaylists(){const root=$("playlist-nav");root.innerHTML="";playlists.playlists.forEach(p=>{const b=document.createElement("button");b.className="nav-item";b.innerHTML='<span class="playlist-dot"></span><span></span>';b.children[1].textContent=p.name;b.onclick=()=>{queue.setItems(p.items.map(x=>library.items.find(i=>i.id===x.id)).filter(Boolean));setView("player");if(queue.current())playItem(queue.current(),0)};root.append(b)});icons()}
new KeyboardShortcuts({play:()=>engine.toggle(),back:()=>engine.skip(-5),forward:()=>engine.skip(5),volumeUp:()=>engine.setVolume(engine.el.volume+.05),volumeDown:()=>engine.setVolume(engine.el.volume-.05),mute:()=>engine.toggleMute(),next,previous,fullscreen:()=>fullscreen.toggle(),equalizer:openEQModal,command:openCommandModal}).init();
registerPWA();session.init({next,previous,play:()=>engine.play(),pause:()=>engine.pause(),seek:seconds=>engine.skip(seconds)});renderPlaylists();icons();setView("home");