import {PlayerState} from "./core/PlayerState.js";
import {MediaEngine} from "./core/MediaEngine.js";
import {QueueManager} from "./core/QueueManager.js";
import {PlaylistManager} from "./core/PlaylistManager.js";
import {LibraryManager} from "./core/LibraryManager.js";
import {IndexedDBStore} from "./storage/IndexedDB.js";
import {Toast} from "./ui/Toast.js";
import {QueueUI} from "./ui/QueueUI.js";
import {LibraryUI} from "./ui/LibraryUI.js";
import {AudioEngine} from "./audio/AudioEngine.js";
import {Equalizer} from "./audio/Equalizer.js";
import {Visualizer} from "./audio/Visualizer.js";
import {VideoFilters} from "./video/VideoFilters.js";
import {SubtitleManager} from "./video/SubtitleManager.js";
import {Screenshot} from "./video/Screenshot.js";
import {ThemeManager} from "./features/ThemeManager.js";
import {FullscreenManager} from "./features/FullscreenManager.js";
import {KeyboardShortcuts} from "./features/KeyboardShortcuts.js";

const $=id=>document.getElementById(id);
const state=new PlayerState(),store=new IndexedDBStore(),toast=new Toast($("toast-root"));
const media=$("media-element"),engine=new MediaEngine(media,state),queue=new QueueManager(),library=new LibraryManager(store),playlists=new PlaylistManager(store);
const theme=new ThemeManager();theme.init();
const audio=new AudioEngine(media),visualizer=new Visualizer($("visualizer-canvas"),audio),filters=new VideoFilters(media),subtitles=new SubtitleManager(media),shot=new Screenshot(media),fullscreen=new FullscreenManager($("media-canvas"));

function icons(){window.lucide?.createIcons?.()}
function formatTime(s){s=Math.max(0,Math.floor(s||0));return Math.floor(s/60)+":"+String(s%60).padStart(2,"0")}
function safeName(s){return String(s||"").replace(/</g,"&lt;").replace(/>/g,"&gt;")}

const playerUI={
 play:$("play-btn"),stagePlay:$("stage-play"),seek:$("seek-range"),volume:$("volume-range"),mute:$("mute-btn"),prev:$("prev-btn"),next:$("next-btn"),shuffle:$("shuffle-btn"),repeat:$("repeat-btn"),speed:$("speed-btn"),fullscreen:$("fullscreen-btn"),pip:$("pip-btn"),stage:$("media-canvas"),current:$("current-time"),duration:$("duration-time"),nowTitle:$("now-title"),nowMeta:$("now-meta"),mini:$("mini-player"),miniTitle:$("mini-title"),miniMeta:$("mini-meta"),miniPlay:$("mini-play"),miniPrev:$("mini-prev"),miniNext:$("mini-next"),miniBar:$("mini-progress-bar"),art:$("artwork-fallback"),miniArt:$("mini-art")
};
function renderState(s){playerUI.play.innerHTML=s.isPlaying?'<i data-lucide="pause"></i>':'<i data-lucide="play"></i>';playerUI.stagePlay.innerHTML=s.isPlaying?'<i data-lucide="pause"></i>':'<i data-lucide="play"></i>';playerUI.stagePlay.classList.toggle("hidden",!s.media);playerUI.nowTitle.textContent=s.media?.title||"Nothing playing";playerUI.nowMeta.textContent=s.media?((s.media.artist||"Local file")+" • "+s.media.type.toUpperCase()):"Select media from your library";playerUI.current.textContent=formatTime(s.currentTime);playerUI.duration.textContent=formatTime(s.duration);playerUI.seek.value=s.duration?(s.currentTime/s.duration)*100:0;playerUI.volume.value=s.volume;playerUI.speed.textContent=(s.rate||1)+"×";playerUI.mute.innerHTML='<i data-lucide="'+(s.muted||s.volume===0?"volume-x":"volume-2")+'"></i>';playerUI.mini.classList.toggle("hidden",!s.media);playerUI.miniTitle.textContent=s.media?.title||"Nothing playing";playerUI.miniMeta.textContent=s.media?.artist||"Local file";playerUI.miniBar.style.width=(s.duration?(s.currentTime/s.duration)*100:0)+"%";$("video-badge").classList.toggle("hidden",s.media?.type!=="video");if(s.media?.type==="audio"){$("artwork-fallback").classList.remove("hidden");media.classList.add("audio-mode")}else{$("artwork-fallback").classList.add("hidden");media.classList.remove("audio-mode")}icons()}
function setView(view){state.patch({view});document.querySelectorAll(".nav-item[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===view));$("player-view").classList.toggle("hidden",view!=="player");$("library-view").classList.toggle("hidden",view==="player");const titles={home:["YOUR LIBRARY","Home","Open local media and build your personal library."],music:["AUDIO COLLECTION","Music","All audio files in your library."],videos:["VIDEO COLLECTION","Videos","All video files in your library."],favorites:["YOUR FAVORITES","Favorites","Media you marked as favorite."],history:["RECENTLY PLAYED","History","Your local playback history."]};const d=titles[view]||titles.home;$("view-eyebrow").textContent=d[0];$("view-title").textContent=d[1];$("view-description").textContent=d[2];renderLibrary(view)}
function renderLibrary(view="home",query=""){let items=library.search(query);if(view==="music")items=items.filter(i=>i.type==="audio");if(view==="videos")items=items.filter(i=>i.type==="video");if(view==="favorites")items=items.filter(i=>i.favorite);libUI.render(items)}
async function playItem(item,index=-1){if(index>=0)queue.index=index;else{const found=queue.items.findIndex(x=>x.id===item.id);if(found<0){queue.add(item)}queue.index=queue.items.findIndex(x=>x.id===item.id)}setView("player");await engine.load(item,true).catch(()=>{});try{await audio.resume();visualizer.start()}catch{}}
function next(){const item=queue.next();if(item)playItem(item,queue.index)}
function previous(){const item=queue.previous();if(item)playItem(item,queue.index)}
const libUI=new LibraryUI($("media-grid"),$("empty-state"),library,{play:playItem,queue:item=>{queue.add(item);toast.show("Added to queue")},favorite:item=>{library.toggleFavorite(item.id)}}),queueUI=new QueueUI($("queue-list"),$("queue-empty"),$("queue-count"),queue,{select:i=>{queue.index=i;playItem(queue.current(),i)}});

await store.open();await library.init();await playlists.init();
$("music-count").textContent=library.items.filter(i=>i.type==="audio").length;$("video-count").textContent=library.items.filter(i=>i.type==="video").length;
library.on(items=>{$("music-count").textContent=items.filter(i=>i.type==="audio").length;$("video-count").textContent=items.filter(i=>i.type==="video").length;renderLibrary(state.data.view)});
state.subscribe(renderState);
[
["open-import",()=>$("file-input").click()],["browse-library",()=>$("file-input").click()],["drop-browse",()=>$("file-input").click()],["empty-browse",()=>$("file-input").click()],
["clear-queue",()=>{queue.clear();toast.show("Queue cleared")}],
["fullscreen",()=>fullscreen.toggle()],["fullscreen-btn",()=>fullscreen.toggle()]
].forEach(([id,fn])=>$(id)?.addEventListener("click",fn));
$("pip-btn").addEventListener("click",()=>{media.requestPictureInPicture?.().catch(()=>toast.show("Picture in Picture is unavailable","error"))});
$("stage-play").addEventListener("click",()=>engine.toggle().catch(()=>toast.show("Press play again to start playback","error")));
$("play-btn").addEventListener("click",()=>engine.toggle().catch(()=>{}));$("mini-play").addEventListener("click",()=>engine.toggle().catch(()=>{}));
$("prev-btn").addEventListener("click",previous);$("mini-prev").addEventListener("click",previous);$("next-btn").addEventListener("click",next);$("mini-next").addEventListener("click",next);
$("seek-range").addEventListener("input",e=>engine.seek(engine.duration*(Number(e.target.value)/100)));$("volume-range").addEventListener("input",e=>engine.setVolume(e.target.value));$("mute-btn").addEventListener("click",()=>engine.toggleMute());
$("shuffle-btn").addEventListener("click",()=>{queue.setShuffle(!queue.shuffle);$("shuffle-btn").classList.toggle("active",queue.shuffle)});
$("repeat-btn").addEventListener("click",()=>{const v=queue.repeat==="off"?"all":queue.repeat==="all"?"one":"off";queue.setRepeat(v);$("repeat-btn").classList.toggle("active",v!=="off");toast.show("Repeat: "+v)});
$("speed-btn").addEventListener("click",()=>{const r=[.5,.75,1,1.25,1.5,1.75,2],i=r.indexOf(media.playbackRate);engine.setRate(r[(i+1)%r.length])});
media.addEventListener("ended",()=>next());media.addEventListener("error",()=>toast.show("This browser could not decode the selected media","error"));
$("file-input").addEventListener("change",async e=>{const files=[...e.target.files];if(!files.length)return;const added=await library.addFiles(files);queue.addMany(added);toast.show(added.length+" media item"+(added.length===1?"":"s")+" added");e.target.value=""});
const dz=$("drop-zone");["dragenter","dragover"].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add("is-over")}));["dragleave","drop"].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();if(ev==="drop"&&e.dataTransfer.files.length)library.addFiles([...e.dataTransfer.files]).then(a=>{queue.addMany(a);toast.show(a.length+" media item(s) added")});dz.classList.remove("is-over")}));
document.addEventListener("dragover",e=>e.preventDefault());
$("global-search").addEventListener("input",e=>renderLibrary(state.data.view,e.target.value));
$("sort-library").addEventListener("click",()=>{library.items.sort((a,b)=>a.title.localeCompare(b.title));libUI.render(library.items)});
document.querySelectorAll(".nav-item[data-view]").forEach(b=>b.addEventListener("click",()=>{setView(b.dataset.view);$("sidebar").classList.remove("open")}));
$("sidebar-toggle").addEventListener("click",()=>document.body.classList.toggle("sidebar-open"));
$("mini-close").addEventListener("click",()=>{$("mini-player").classList.add("hidden")});
$("tool-screenshot").addEventListener("click",()=>{try{shot.capture();toast.show("Frame captured")}catch(e){toast.show(e.message,"error")}});
$("tool-subtitles").addEventListener("click",()=>{$("subtitle-input").click()});$("subtitle-input").addEventListener("change",e=>{const f=e.target.files[0];if(f){subtitles.load(f);toast.show("Subtitle loaded")}});
$("tool-video").addEventListener("click",()=>openVideoModal());$("tool-eq").addEventListener("click",()=>openEQModal());$("tool-info").addEventListener("click",()=>openInfoModal());$("tool-ab").addEventListener("click",()=>toast.show("A–B marker: use the current playhead as point A/B in the next iteration"));
$("open-equalizer").addEventListener("click",openEQModal);$("open-settings").addEventListener("click",openSettingsModal);$("open-command").addEventListener("click",openCommandModal);$("open-shortcuts").addEventListener("click",()=>toast.show("Space play/pause • ←/→ seek • ↑/↓ volume • M mute • N next • P previous • F fullscreen • E equalizer"));
$("new-playlist").addEventListener("click",async()=>{const name=prompt("Playlist name");if(name){await playlists.create(name);renderPlaylists();toast.show("Playlist created")}});
function modal(title,body,actions=""){const root=$("modal-root");root.innerHTML='<div class="modal-backdrop"><div class="modal">'+title+body+actions+"</div></div>";const bd=root.firstElementChild;bd.addEventListener("click",e=>{if(e.target===bd)root.innerHTML=""});root.querySelectorAll("[data-close]").forEach(b=>b.addEventListener("click",()=>root.innerHTML=""));icons()}
function openEQModal(){const bands=[60,170,310,600,1000,3000,6000,10000,14000,16000];modal(" <div class='modal-head'><div class='modal-title'>10-Band Equalizer</div><button class='icon-btn' data-close>×</button></div>","<div class='modal-body'><div class='eq-grid'>"+bands.map((b,i)=>"<label class='eq-band'><input data-band='"+i+"' type='range' min='-12' max='12' value='0' step='1'><span>"+(b>=1000?(b/1000)+"k":b)+"</span></label>").join("")+"</div><div style='display:flex;gap:8px;flex-wrap:wrap;margin-top:12px'>"+["Flat","Rock","Pop","Bass","Vocal"].map(p=>"<button class='soft-btn' data-preset='"+p+"'>"+p+"</button>").join("")+"</div></div>","<div class='modal-actions'><button class='primary-btn' data-close>Done</button></div>");try{audio.ensure()}catch{}document.querySelectorAll("[data-band]").forEach(x=>x.addEventListener("input",e=>audio.setBand(Number(e.target.dataset.band),e.target.value)));document.querySelectorAll("[data-preset]").forEach(x=>x.addEventListener("click",()=>{const vals=new Equalizer(audio).presets[x.dataset.preset];vals.forEach((v,i)=>{audio.setBand(i,v);const el=document.querySelector('[data-band="'+i+'"]');if(el)el.value=v})}))}
function openVideoModal(){modal("<div class='modal-head'><div class='modal-title'>Video filters</div><button class='icon-btn' data-close>×</button></div>","<div class='modal-body'><div class='field'><label>Brightness</label><input data-filter='brightness' type='range' min='50' max='150' value='100'></div><div class='field'><label>Contrast</label><input data-filter='contrast' type='range' min='50' max='150' value='100'></div><div class='field'><label>Saturation</label><input data-filter='saturation' type='range' min='0' max='200' value='100'></div><div class='field'><label>Hue</label><input data-filter='hue' type='range' min='-90' max='90' value='0'></div><div class='modal-actions'><button id='reset-filters' class='soft-btn'>Reset</button><button class='primary-btn' data-close>Done</button></div></div>");document.querySelectorAll("[data-filter]").forEach(x=>x.addEventListener("input",e=>filters.set(e.target.dataset.filter,e.target.value)));$("reset-filters").addEventListener("click",()=>{filters.reset();document.querySelectorAll("[data-filter]").forEach(x=>x.value=filters.values[x.dataset.filter])})}
function openInfoModal(){const i=state.data.media;if(!i)return toast.show("Nothing is playing","error");modal("<div class='modal-head'><div class='modal-title'>Media information</div><button class='icon-btn' data-close>×</button></div>","<div class='modal-body'><div class='settings-section'><div class='setting-line'><div class='setting-copy'><strong>Name</strong><span>"+safeName(i.name)+"</span></div></div><div class='setting-line'><div class='setting-copy'><strong>Type</strong><span>"+i.type+" • "+i.mime+"</span></div></div><div class='setting-line'><div class='setting-copy'><strong>Duration</strong><span>"+formatTime(i.duration)+"</span></div></div><div class='setting-line'><div class='setting-copy'><strong>Size</strong><span>"+(i.size/1024/1024).toFixed(2)+" MB</span></div></div></div></div>","<div class='modal-actions'><button class='primary-btn' data-close>Close</button></div>")}
function openSettingsModal(){modal("<div class='modal-head'><div class='modal-title'>AURA Settings</div><button class='icon-btn' data-close>×</button></div>","<div class='modal-body'><div class='settings-layout'><nav class='settings-nav'><button class='settings-tab active'>Appearance</button><button class='settings-tab'>Playback</button><button class='settings-tab'>Storage</button></nav><div class='settings-section'><div class='setting-line'><div class='setting-copy'><strong>Theme</strong><span>Choose the application appearance</span></div><select id='theme-select'><option value='dark'>Dark</option><option value='light'>Light</option></select></div><div class='setting-line'><div class='setting-copy'><strong>Visualizer</strong><span>Show frequency bars while audio is playing</span></div><label class='switch'><input id='viz-switch' type='checkbox' checked><span></span></label></div></div></div></div>","<div class='modal-actions'><button class='primary-btn' data-close>Done</button></div>");$("theme-select").value=document.body.dataset.theme;$("theme-select").addEventListener("change",e=>theme.set(e.target.value));$("viz-switch").addEventListener("change",e=>e.target.checked?visualizer.start():visualizer.stop())}
function openCommandModal(){modal("<div class='modal-head'><div class='modal-title'>Command Palette</div><button class='icon-btn' data-close>×</button></div>","<div class='modal-body'><div class='field'><input id='command-search' autofocus placeholder='Search commands…'></div><div id='command-list' class='command-list'></div></div>");const commands=[["Play / Pause",()=>engine.toggle()],["Next",next],["Previous",previous],["Fullscreen",()=>fullscreen.toggle()],["Equalizer",openEQModal],["Add media",()=>$("file-input").click()],["Home",()=>setView("home")]];const draw=q=>{const list=$("command-list");list.innerHTML="";commands.filter(x=>x[0].toLowerCase().includes(q.toLowerCase())).forEach(x=>{const b=document.createElement("button");b.className="nav-item";b.textContent=x[0];b.onclick=()=>{$("modal-root").innerHTML="";x[1]()};list.append(b)})};$("command-search").addEventListener("input",e=>draw(e.target.value));draw("");$("command-search").focus()}
function renderPlaylists(){const root=$("playlist-nav");root.innerHTML="";playlists.playlists.forEach(p=>{const b=document.createElement("button");b.className="nav-item";b.innerHTML='<span class="playlist-dot"></span><span></span>';b.children[1].textContent=p.name;b.onclick=()=>{queue.setItems(p.items.map(x=>library.items.find(i=>i.id===x.id)).filter(Boolean));setView("player");if(queue.current())playItem(queue.current(),0)};root.append(b)});icons()}
new KeyboardShortcuts({play:()=>engine.toggle(),back:()=>engine.skip(-5),forward:()=>engine.skip(5),volumeUp:()=>engine.setVolume(engine.el.volume+.05),volumeDown:()=>engine.setVolume(engine.el.volume-.05),mute:()=>engine.toggleMute(),next,previous,fullscreen:()=>fullscreen.toggle(),equalizer:openEQModal,command:openCommandModal}).init();
renderPlaylists();icons();setView("home");